# Generated by Django 4.1.3 on 2022-11-21 19:52

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефону')),
                ('type_phone', models.CharField(choices=[('Моб', 'Мобільний'), ('Дом', 'Домашній'), ('Роб', 'Робочий'), ('Дод', 'Додатковий')], default='Моб', max_length=3, verbose_name='Тип номеру телефону')),
                ('verification', models.CharField(choices=[('Осн', 'Основний'), ('Акт', 'Активний'), ('Пас', 'Пасивний')], default='Акт', max_length=8, verbose_name='Верифікація')),
                ('facetime', models.BooleanField(default=False, verbose_name='FaceTime')),
                ('signal', models.BooleanField(default=False, verbose_name='Signal')),
                ('telegram', models.BooleanField(default=False, verbose_name='Telegram')),
                ('viber', models.BooleanField(default=False, verbose_name='Viber')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Номер телефону клієнта',
                'verbose_name_plural': 'Номери телефонів клієнтів',
                'db_table': 'clients_phones',
                'unique_together': {('client', 'type_phone'), ('client', 'phone', 'verification'), ('client', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Електронна пошта клієнта',
                'verbose_name_plural': 'Електронні пошти клієнта',
                'db_table': 'client_email',
                'unique_together': {('client', 'email')},
            },
        ),
        migrations.CreateModel(
            name='ClientContactPersonPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефону')),
                ('type_phone', models.CharField(choices=[('Моб', 'Мобільний'), ('Дом', 'Домашній'), ('Роб', 'Робочий'), ('Дод', 'Додатковий')], default='Моб', max_length=3, verbose_name='Тип номеру телефону')),
                ('verification', models.CharField(choices=[('Осн', 'Основний'), ('Акт', 'Активний'), ('Пас', 'Пасивний')], default='Акт', max_length=8, verbose_name='Верифікація')),
                ('facetime', models.BooleanField(default=False, verbose_name='FaceTime')),
                ('signal', models.BooleanField(default=False, verbose_name='Signal')),
                ('telegram', models.BooleanField(default=False, verbose_name='Telegram')),
                ('viber', models.BooleanField(default=False, verbose_name='Viber')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('сontact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientcontactperson', verbose_name='Контактне лице')),
            ],
            options={
                'verbose_name': 'Телефон контактного лиця клієнта',
                'verbose_name_plural': 'Телефони контактних лиць клієнтів',
                'db_table': 'client_contact_persons_phones',
                'unique_together': {('сontact_person', 'type_phone'), ('сontact_person', 'phone', 'verification'), ('сontact_person', 'phone')},
            },
        ),
    ]
