# Generated by Django 4.1.3 on 2022-11-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcontactperson_relations'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientphone',
            unique_together={('client', 'type_phone'), ('client', 'phone')},
        ),
        migrations.AddField(
            model_name='clientcontactpersonphone',
            name='olx',
            field=models.BooleanField(default=False, verbose_name='OLX'),
        ),
        migrations.AddField(
            model_name='clientcontactpersonphone',
            name='prom',
            field=models.BooleanField(default=False, verbose_name='Prom.ua'),
        ),
        migrations.AddField(
            model_name='clientemail',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Активний'), ('NOT', 'Не активний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
        migrations.AddField(
            model_name='clientphone',
            name='olx',
            field=models.BooleanField(default=False, verbose_name='OLX'),
        ),
        migrations.AddField(
            model_name='clientphone',
            name='prom',
            field=models.BooleanField(default=False, verbose_name='Prom.ua'),
        ),
        migrations.AlterField(
            model_name='clientcontactpersonphone',
            name='type_phone',
            field=models.CharField(choices=[('Моб.', 'Мобільний'), ('Дом.', 'Домашній'), ('Роб.', 'Робочий'), ('Додат.', 'Додатковий')], default='Моб.', max_length=6, verbose_name='Тип номеру телефону'),
        ),
        migrations.AlterField(
            model_name='clientcontactpersonphone',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Активний'), ('NOT', 'Не активний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='type_phone',
            field=models.CharField(choices=[('Моб.', 'Мобільний'), ('Дом.', 'Домашній'), ('Роб.', 'Робочий'), ('Додат.', 'Додатковий')], default='Моб.', max_length=6, verbose_name='Тип номеру телефону'),
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Активний'), ('NOT', 'Не активний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
    ]
