# Generated by Django 4.1.3 on 2022-11-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_clientphone_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontactpersonphone',
            options={'verbose_name': 'Телефон контактної особи клієнта', 'verbose_name_plural': 'Телефони контактних осіб клієнтів'},
        ),
    ]
