# Generated by Django 4.1.3 on 2022-12-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcontactperson_relations'),
        ('contacts', '0003_alter_clientcontactpersonphone_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontactpersonphone',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Валідний'), ('NOT', 'Не валідний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
        migrations.AlterField(
            model_name='clientemail',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Валідний'), ('NOT', 'Не валідний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
        migrations.AlterField(
            model_name='clientphone',
            name='verification',
            field=models.CharField(blank=True, choices=[('YES', 'Валідний'), ('NOT', 'Не валідний')], max_length=3, null=True, verbose_name='Верифікація'),
        ),
        migrations.CreateModel(
            name='ClientContactPersonEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('verification', models.CharField(blank=True, choices=[('YES', 'Валідний'), ('NOT', 'Не валідний')], max_length=3, null=True, verbose_name='Верифікація')),
                ('сontact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientcontactperson', verbose_name='Контактне лице')),
            ],
            options={
                'verbose_name': 'Електронна пошта контактної особи клієнта',
                'verbose_name_plural': 'Електронні пошти контактних осіб клієнтів',
                'db_table': 'client_contact_persons_emails',
            },
        ),
    ]
