# Generated by Django 4.1.3 on 2022-12-06 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcontactperson_relations'),
        ('contacts', '0004_alter_clientcontactpersonphone_verification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontactpersonemail',
            old_name='сontact_person',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='clientcontactpersonphone',
            old_name='сontact_person',
            new_name='contact_person',
        ),
        migrations.AlterUniqueTogether(
            name='clientcontactpersonemail',
            unique_together={('contact_person', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='clientcontactpersonphone',
            unique_together={('contact_person', 'phone'), ('contact_person', 'type_phone'), ('contact_person', 'phone', 'verification')},
        ),
    ]
