# Generated by Django 4.1.1 on 2022-10-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Legal address', 'Юридична адреса'), ('Physical address', 'Адреса реєстрації'), ('Mailing address', 'Адреса проживання'), ('Work address', 'Робоча адреса')], default='Legal address', max_length=16, verbose_name='Тип адреси'),
        ),
    ]
