# Generated by Django 4.1.1 on 2022-11-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientaddress',
            table='ClientAddress',
        ),
    ]
