# Generated by Django 4.1.1 on 2022-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_alter_clientaddress_type_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Company address', 'Адреса компанії клієнта'), ('Legal address', 'Адреса реєстрації клієнта'), ('Physical address', 'Адреса проживання клієнта'), ('Work address', 'Адреса працевлаштування клієнта')], default='Legal address', max_length=16, verbose_name='Тип адреси'),
        ),
    ]
