# Generated by Django 4.1.1 on 2022-11-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0002_alter_clientaddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientaddress',
            table='client_address',
        ),
    ]
