# Generated by Django 4.1.1 on 2022-10-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0003_alter_clientaddress_type_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='district',
            field=models.CharField(blank=True, max_length=50, verbose_name='Район'),
        ),
    ]
