# Generated by Django 4.1.1 on 2022-11-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0003_alter_clientaddress_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='country',
            field=models.CharField(default='Україна', max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='contractoraddress',
            name='country',
            field=models.CharField(default='Україна', max_length=50, verbose_name='Країна'),
        ),
        migrations.AlterField(
            model_name='contractormanageraddress',
            name='country',
            field=models.CharField(default='Україна', max_length=50, verbose_name='Країна'),
        ),
    ]
