# Generated by Django 4.1.1 on 2022-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0004_alter_clientaddress_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='type_street',
            field=models.CharField(choices=[('просп.', 'Проспект'), ('вул.', 'Вулиця'), ('пров.', 'Провулок'), ('б-р.', 'Бульвар'), ('наб.', 'Набережна'), ('туп.', 'Тупик')], default='вул.', max_length=6, verbose_name='Тип вулиці'),
        ),
    ]
