# Generated by Django 4.1.1 on 2022-10-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_managers', '0001_initial'),
        ('contractors', '0003_alter_contractor_edrpou_alter_contractor_title_and_more'),
        ('adresses', '0005_alter_clientaddress_type_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorManagerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_address', models.CharField(blank=True, choices=[('Company address', 'Адреса компанії клієнта'), ('Legal address', 'Адреса реєстрації клієнта'), ('Physical address', 'Адреса проживання клієнта'), ('Work address', 'Адреса працевлаштування клієнта')], default='Legal address', max_length=16, verbose_name='Тип адреси')),
                ('index', models.CharField(blank=True, max_length=8, verbose_name='Індекс')),
                ('country', models.CharField(default='Ukraine', max_length=50, verbose_name='Країна')),
                ('province', models.CharField(max_length=50, verbose_name='Область')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Район')),
                ('type_city', models.CharField(choices=[('с.', 'Село'), ('м.', 'Місто'), ('смт.', 'Селище міського типу')], default='м.', max_length=4, verbose_name='Тип населеного пункту')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('city_district', models.CharField(blank=True, max_length=50, verbose_name='Район-міста')),
                ('type_street', models.CharField(choices=[('просп.', 'Проспект'), ('вул.', 'Вулиця'), ('пров.', 'Провулок'), ('б-р.', 'Бульвар'), ('наб.', 'Набережна'), ('туп.', 'Тупик')], default='вул.', max_length=6, verbose_name='Тип вулиці')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=9, verbose_name='Будинок')),
                ('apartment_type', models.CharField(blank=True, choices=[('кв.', 'Квартира'), ('оф.', 'Офіс')], max_length=9, verbose_name='Тип приміщення')),
                ('apartment_number', models.IntegerField(blank=True, verbose_name='Номер приміщення')),
                ('contractor_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor_managers.contractormanager', verbose_name='Менеджер контрагента')),
            ],
            options={
                'verbose_name': 'Адреса менеджера контрагента',
                'verbose_name_plural': 'Адреси менеджерів контрагентів',
                'db_table': 'contractor_manager_address',
            },
        ),
        migrations.CreateModel(
            name='ContractorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_address', models.CharField(blank=True, choices=[('Company address', 'Адреса компанії клієнта'), ('Legal address', 'Адреса реєстрації клієнта'), ('Physical address', 'Адреса проживання клієнта'), ('Work address', 'Адреса працевлаштування клієнта')], default='Legal address', max_length=16, verbose_name='Тип адреси')),
                ('index', models.CharField(blank=True, max_length=8, verbose_name='Індекс')),
                ('country', models.CharField(default='Ukraine', max_length=50, verbose_name='Країна')),
                ('province', models.CharField(max_length=50, verbose_name='Область')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='Район')),
                ('type_city', models.CharField(choices=[('с.', 'Село'), ('м.', 'Місто'), ('смт.', 'Селище міського типу')], default='м.', max_length=4, verbose_name='Тип населеного пункту')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('city_district', models.CharField(blank=True, max_length=50, verbose_name='Район-міста')),
                ('type_street', models.CharField(choices=[('просп.', 'Проспект'), ('вул.', 'Вулиця'), ('пров.', 'Провулок'), ('б-р.', 'Бульвар'), ('наб.', 'Набережна'), ('туп.', 'Тупик')], default='вул.', max_length=6, verbose_name='Тип вулиці')),
                ('street', models.CharField(max_length=50, verbose_name='Вулиця')),
                ('house', models.CharField(max_length=9, verbose_name='Будинок')),
                ('apartment_type', models.CharField(blank=True, choices=[('кв.', 'Квартира'), ('оф.', 'Офіс')], max_length=9, verbose_name='Тип приміщення')),
                ('apartment_number', models.IntegerField(blank=True, verbose_name='Номер приміщення')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Адреса контрагента',
                'verbose_name_plural': 'Адреси контрагентів',
                'db_table': 'contractor_address',
            },
        ),
    ]
