# Generated by Django 4.1.1 on 2022-10-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0006_contractormanageraddress_contractoraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Company address', 'Адреса компанії'), ('Legal address', 'Адреса реєстрації'), ('Physical address', 'Адреса проживання'), ('Work address', 'Адреса працевлаштування')], default='Legal address', max_length=16, verbose_name='Тип адреси'),
        ),
        migrations.AlterField(
            model_name='contractoraddress',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Company address', 'Адреса компанії'), ('Legal address', 'Адреса реєстрації'), ('Physical address', 'Адреса проживання'), ('Work address', 'Адреса працевлаштування')], default='Legal address', max_length=16, verbose_name='Тип адреси'),
        ),
        migrations.AlterField(
            model_name='contractormanageraddress',
            name='type_address',
            field=models.CharField(blank=True, choices=[('Company address', 'Адреса компанії'), ('Legal address', 'Адреса реєстрації'), ('Physical address', 'Адреса проживання'), ('Work address', 'Адреса працевлаштування')], default='Legal address', max_length=16, verbose_name='Тип адреси'),
        ),
    ]
