# Generated by Django 4.1.1 on 2022-10-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0007_alter_clientaddress_type_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер приміщення'),
        ),
        migrations.AlterField(
            model_name='contractoraddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер приміщення'),
        ),
        migrations.AlterField(
            model_name='contractormanageraddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер приміщення'),
        ),
    ]
