# Generated by Django 4.1.1 on 2022-10-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_unique_together'),
        ('adresses', '0008_alter_clientaddress_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together={('client', 'type_address')},
        ),
    ]
