# Generated by Django 4.1.1 on 2022-10-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_unique_together'),
        ('adresses', '0009_alter_clientaddress_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientaddress',
            old_name='client',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='contractoraddress',
            old_name='contractor',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='contractormanageraddress',
            old_name='contractor_manager',
            new_name='person',
        ),
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together={('person', 'type_address')},
        ),
    ]
