# Generated by Django 4.1.1 on 2022-10-30 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adresses', '0010_rename_client_clientaddress_person_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together=set(),
        ),
    ]
