# Generated by Django 4.1.1 on 2022-10-30 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0003_alter_contractor_edrpou_alter_contractor_title_and_more'),
        ('clients', '0004_alter_client_unique_together'),
        ('contractor_managers', '0001_initial'),
        ('adresses', '0011_alter_clientaddress_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientaddress',
            unique_together={('person', 'type_address')},
        ),
        migrations.AlterUniqueTogether(
            name='contractoraddress',
            unique_together={('person', 'type_address')},
        ),
        migrations.AlterUniqueTogether(
            name='contractormanageraddress',
            unique_together={('person', 'type_address')},
        ),
    ]
