create_form_fields = [
                    'last_name',
                    'first_name',
                    'patronymic',
                    'date_of_birth',
                    'primary_phone_number',
                    'additional_phone_number',
                    'work_phone_number',
                    'home_phone_number',
                    'email',
                    'ipn',
                    'passport_serial',
                    'passport_number',
                    'employer',
                    'position',
                    'created_date',
                    'update_date',
                    ]
