# Generated by Django 4.1.1 on 2022-09-23 19:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('МФО', 'Мікрофінансова організація'), ('ФК', 'Факторингова компанія'), ('БУ', 'Банкова установа'), ('СК', 'Страхова компанія'), ('ТК', 'Телекомунікаційна компанія'), ('ЖКГ', 'Житлово-комунальне гопподарство')], max_length=4, verbose_name='Тип контрагента')),
                ('edrpou', models.IntegerField(max_length=6, verbose_name='ЄДРПОУ')),
                ('title', models.CharField(max_length=10, verbose_name='Назва компанії')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефону')),
                ('address', models.JSONField(blank=True, verbose_name='Адреса')),
                ('post_address', models.JSONField(blank=True, verbose_name='Поштова адреса')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('primary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Основний номер телефону')),
                ('additional_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Додатковий номер телефону')),
                ('work_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Робочий номер телефону')),
                ('home_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Домашній номер телефону')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('position', models.CharField(max_length=50, verbose_name='Посада')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractor.contractor', verbose_name='Контрагент')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
