# Generated by Django 4.1.1 on 2022-09-29 17:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('МФО', 'Мікрофінансова організація'), ('ФК', 'Факторингова компанія'), ('БУ', 'Банкова установа'), ('СК', 'Страхова компанія'), ('ТК', 'Телекомунікаційна компанія'), ('ЖКГ', 'Житлово-комунальне гопподарство')], max_length=4, verbose_name='Тип контрагента')),
                ('edrpou', models.IntegerField(verbose_name='ЄДРПОУ')),
                ('title', models.CharField(max_length=50, verbose_name='Назва компанії')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефону')),
                ('address', models.JSONField(blank=True, null=True, verbose_name='Адреса')),
                ('post_address', models.JSONField(blank=True, null=True, verbose_name='Поштова адреса')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
                'db_table': 'contractor',
            },
        ),
    ]
