# Generated by Django 4.1.1 on 2022-10-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Назва компанії'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='type',
            field=models.CharField(choices=[('МФО', 'Мікрофінансова організація'), ('ФК', 'Факторингова компанія'), ('БУ', 'Банкова установа'), ('СК', 'Страхова компанія'), ('ТК', 'Телекомунікаційна компанія'), ('ЖКГ', 'Житлово-комунальне гопподарство')], default='МФО', max_length=3, verbose_name='Тип контрагента'),
        ),
    ]
