# Generated by Django 4.1.1 on 2022-09-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='edrpou',
            field=models.IntegerField(verbose_name='ЄДРПОУ'),
        ),
    ]
