# Generated by Django 4.1.1 on 2022-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_alter_contractor_edrpou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Назва компанії'),
        ),
    ]
