# Generated by Django 4.1.3 on 2022-12-16 15:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IN', 'Вхідний'), ('OUT', 'Вихідний')], max_length=3, verbose_name='Тип комунікації')),
                ('action', models.CharField(choices=[('CALL', 'Дзвінок'), ('MESS', 'Повідомлення'), ('LETT', 'Лист'), ('IVM', 'Голосове повідомлення')], max_length=12, verbose_name='Дія')),
                ('communication_channel', models.CharField(choices=[('Дзвінок', (('phone', 'Телефон'), ('facetime', 'FaceTime'), ('signal', 'Signal'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'))), ('Повідомлення', (('SMS', 'СМС'), ('facetime', 'FaceTime'), ('signal', 'Signal'), ('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'))), ('Лист', (('email', 'Електронний лист'), ('mail', 'Поштовий лист')))], max_length=16, verbose_name='Канал звязку')),
                ('communication_detail', models.CharField(max_length=100, verbose_name='Деталі')),
                ('person', models.CharField(default='Клієнт', max_length=255, verbose_name='Контактна особа')),
                ('result', models.CharField(choices=[('Результативний дзвінок', (('HU', 'Поклали слухавку'), ('DRD', 'Не визнає борг'), ('DNC', 'Клієнта не знають'), ('BPO', 'Передадуть інформацію'), ('STD', 'Передано інформацію боржнику'))), ('Успішний дзвінок', (('PTP', 'Обіцянка сплатити'), ('PTE', 'Обіцянка продовження'), ('RTL', 'Реструтуризація'))), ('Не результативний дзвінок', (('ANPH', 'Автовідповідач'), ('DROP', 'Зрив дзвінка'), ('NINS', 'Номер не обслуговується'), ('INNU', 'Не вірно набранний номер'))), ('Повідомлення/Лист', (('SEND', 'Відправлено'), ('RCVD', 'Отримано'), ('ANSW', 'Отримано відповідь'), ('NVLD', 'Не вірні контактні дані'))), ('Голосове повідомлення', (('', 'IVM неуспішний'), ('', 'IVM повністю прослухано'), ('', 'IVM частково прослухано')))], max_length=4, verbose_name='Результат')),
                ('sum', models.IntegerField(blank=True, null=True, verbose_name='Обіцяна сума погашення')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='Обіцяна дата погашення')),
                ('comment', models.TextField(verbose_name='Коментар/Текст')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='debts.debt', verbose_name='Справа')),
            ],
            options={
                'verbose_name': 'Комунікація',
                'verbose_name_plural': 'Комунікації',
                'db_table': 'communications',
            },
        ),
    ]
