# Generated by Django 4.1.3 on 2023-01-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='debt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='communications', to='debts.debt', verbose_name='Справа'),
        ),
    ]
