# Generated by Django 4.1.3 on 2022-11-21 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('position', models.CharField(max_length=50, verbose_name='Посада')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractors.contractor', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Менеджер контрагента',
                'verbose_name_plural': 'Менеджери контрагентів',
                'db_table': 'сontractor_manager',
            },
        ),
    ]
