# Generated by Django 4.1.1 on 2022-11-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractormanager',
            name='gender',
            field=models.CharField(choices=[('F.', 'Жіночий'), ('M.', 'Чоловічий'), ('N', 'Не вказано')], default='N', max_length=2),
        ),
    ]
