# Generated by Django 4.1.1 on 2022-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_managers', '0002_contractormanager_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormanager',
            name='gender',
            field=models.CharField(choices=[('F', 'Жіночий'), ('M', 'Чоловічий'), ('N', 'Не вказано')], default='N', max_length=2),
        ),
    ]
