# Generated by Django 4.1.1 on 2022-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor_managers', '0003_alter_contractormanager_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractormanager',
            name='gender',
            field=models.CharField(choices=[('Жіноча', 'Жіноча'), ('Чоловіча', 'Чоловіча'), ('Не вказана', 'Не вказана')], default='Не вказана', max_length=10),
        ),
    ]
