# Generated by Django 4.1.1 on 2022-10-30 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('primary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Основний номер телефону')),
                ('additional_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Додатковий номер телефону')),
                ('work_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Робочий номер телефону')),
                ('home_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Домашній номер телефону')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('ipn', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ІПН')),
                ('passport_serial', models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія паспорту')),
                ('passport_number', models.IntegerField(blank=True, null=True, verbose_name='Номер паспорту')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роботодавець')),
                ('position', models.CharField(blank=True, max_length=128, null=True, verbose_name='Посада')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата внесення в реєстр')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'clients',
                'unique_together': {('passport_serial', 'passport_number')},
            },
        ),
        migrations.CreateModel(
            name='ClientStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('military', models.BooleanField(default=False, verbose_name='Військовий')),
                ('displaced', models.BooleanField(default=False, verbose_name='Тимчасово переміщений')),
                ('abroad', models.BooleanField(default=False, verbose_name='Віїхав за кордон')),
                ('occupation', models.BooleanField(default=False, verbose_name='Під окупацією')),
                ('credited', models.BooleanField(default=False, verbose_name='Закредитований')),
                ('bankrupt', models.BooleanField(default=False, verbose_name='Банкрот')),
                ('imprisoned', models.BooleanField(default=False, verbose_name='Тюрма')),
                ('illness', models.BooleanField(default=False, verbose_name='Хвороба')),
                ('death', models.BooleanField(default=False, verbose_name='Смерть')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Статуси клієнта',
                'verbose_name_plural': 'Статуси клієнтів',
                'db_table': 'client_statuses',
            },
        ),
        migrations.CreateModel(
            name='ClientSocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=128, unique=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, max_length=128, unique=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, max_length=128, unique=True, verbose_name='Instagram')),
                ('tictok', models.URLField(blank=True, max_length=128, unique=True, verbose_name='Tik Tok')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Соціальні мережі клієнта',
                'verbose_name_plural': 'Соціальні мережі клієнтів',
                'db_table': 'client_social_networks',
            },
        ),
    ]
