# Generated by Django 4.1.3 on 2022-11-21 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('gender', models.CharField(choices=[('Жін', 'Жіноча'), ('Чол', 'Чоловіча'), ('Інше', 'Інше')], max_length=4, verbose_name='Стать')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('ipn', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ІПН')),
                ('passport_serial', models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія паспорту')),
                ('passport_number', models.IntegerField(blank=True, null=True, verbose_name='Номер паспорту')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роботодавець')),
                ('position', models.CharField(blank=True, max_length=128, null=True, verbose_name='Посада')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата внесення в реєстр')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'clients',
                'unique_together': {('passport_serial', 'passport_number')},
            },
        ),
        migrations.CreateModel(
            name='ClientSocialNetworks',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт')),
                ('facebook', models.URLField(blank=True, max_length=128, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, max_length=128, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, max_length=128, verbose_name='Instagram')),
                ('tictok', models.URLField(blank=True, max_length=128, verbose_name='Tik Tok')),
            ],
            options={
                'verbose_name': 'Соціальні мережі клієнта',
                'verbose_name_plural': 'Соціальні мережі клієнтів',
                'db_table': 'client_social_networks',
            },
        ),
        migrations.CreateModel(
            name='ClientStatuses',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт')),
                ('military', models.BooleanField(default=False, verbose_name='Військовий')),
                ('displaced', models.BooleanField(default=False, verbose_name='Тимчасово переміщений')),
                ('abroad', models.BooleanField(default=False, verbose_name='Виїхав за кордон')),
                ('occupation', models.BooleanField(default=False, verbose_name='Під окупацією')),
                ('credited', models.BooleanField(default=False, verbose_name='Закредитований')),
                ('bankrupt', models.BooleanField(default=False, verbose_name='Банкрот')),
                ('imprisoned', models.BooleanField(default=False, verbose_name='Тюрма')),
                ('illness', models.BooleanField(default=False, verbose_name='Хвороба')),
                ('death', models.BooleanField(default=False, verbose_name='Смерть')),
            ],
            options={
                'verbose_name': 'Статуси клієнта',
                'verbose_name_plural': 'Статуси клієнтів',
                'db_table': 'client_statuses',
            },
        ),
        migrations.CreateModel(
            name='ClientContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('relations', models.CharField(choices=[('Close relatives', 'Близькі родичі'), ('Distant relatives', 'Далекі родичі'), ('Friends', 'Друзі'), ('Colleagues', 'Колеги'), ('Neighbors', 'Сусіди')], max_length=17, verbose_name='Тип звязку')),
                ('priority', models.BooleanField(default=False, verbose_name='Основний контакт')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Додатковий контакт клієнта',
                'verbose_name_plural': 'Додаткові контакти клієнтів',
                'db_table': 'clients_contacts_persons',
                'unique_together': {('client', 'last_name', 'first_name', 'patronymic')},
            },
        ),
    ]
