# Generated by Django 4.1.1 on 2022-09-27 07:03

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='По-батькові')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('primary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Основний номер телефону')),
                ('additional_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Додатковий номер телефону')),
                ('work_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Робочий номер телефону')),
                ('home_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Домашній номер телефону')),
                ('email', models.EmailField(max_length=255, verbose_name='Електронна пошта')),
                ('ipn', models.BigIntegerField(blank=True, null=True, verbose_name='ІПН')),
                ('passport_serial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серія паспорту')),
                ('passport_number', models.IntegerField(blank=True, verbose_name='Номер паспорту')),
                ('addresses', models.JSONField(blank=True, null=True, verbose_name='Адреси')),
                ('employer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Роботодавець')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата внесення в реєстр')),
                ('update_date', models.DateTimeField(blank=True, verbose_name='Дата оновлення')),
                ('number_of_debts', models.IntegerField(blank=True, null=True, verbose_name='Кількість справ')),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
