# Generated by Django 4.1.1 on 2022-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ipn',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ІПН'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_serial',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Серія паспорту'),
        ),
    ]
