# Generated by Django 4.1.1 on 2022-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatuses',
            name='abroad',
            field=models.BooleanField(default=False, verbose_name='Виїхав за кордон'),
        ),
    ]
