# Generated by Django 4.1.3 on 2022-12-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcontactperson_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontactperson',
            options={'verbose_name': 'Повязана особа', 'verbose_name_plural': 'Повязані особи'},
        ),
    ]
