# Generated by Django 4.1.1 on 2022-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_ipn_alter_client_passport_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер паспорту'),
        ),
    ]
