# Generated by Django 4.1.3 on 2022-12-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientcontactperson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontactperson',
            name='relations',
            field=models.CharField(choices=[('Близькі родичі', 'Близькі родичі'), ('Далекі родичі', 'Далекі родичі'), ('Друзі', 'Друзі'), ('Коллеги', 'Коллеги'), ('Сусіди', 'Сусіди'), ('Поручитель', 'Поручитель'), ('Заставодавець', 'Заставодавець')], max_length=14, verbose_name='Тип звязку'),
        ),
    ]
