# Generated by Django 4.1.1 on 2022-10-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_passport_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('passport_serial', 'passport_number')},
        ),
    ]
