# Generated by Django 4.1.1 on 2022-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Жіноча', 'Жіноча'), ('Чоловіча', 'Чоловіча'), ('Не вказана', 'Не вказана')], default='Не вказана', max_length=10),
        ),
    ]
