# Generated by Django 4.1.1 on 2022-10-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStatuses',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт')),
                ('military', models.BooleanField(default=False, verbose_name='Військовий')),
                ('displaced', models.BooleanField(default=False, verbose_name='Тимчасово переміщений')),
                ('abroad', models.BooleanField(default=False, verbose_name='Віїхав за кордон')),
                ('occupation', models.BooleanField(default=False, verbose_name='Під окупацією')),
                ('credited', models.BooleanField(default=False, verbose_name='Закредитований')),
                ('bankrupt', models.BooleanField(default=False, verbose_name='Банкрот')),
                ('imprisoned', models.BooleanField(default=False, verbose_name='Тюрма')),
                ('illness', models.BooleanField(default=False, verbose_name='Хвороба')),
                ('death', models.BooleanField(default=False, verbose_name='Смерть')),
            ],
        ),
    ]
