# Generated by Django 4.1.1 on 2022-10-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientstatuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientstatuses',
            options={'verbose_name': 'Статуси клієнта', 'verbose_name_plural': 'Статуси клієнтів'},
        ),
        migrations.AlterModelTable(
            name='clientstatuses',
            table='client_statuses',
        ),
    ]
