# Generated by Django 4.1.1 on 2022-11-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_gender'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientstatuses',
            table='statuses',
        ),
    ]
