# Generated by Django 4.1.1 on 2022-11-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clientstatuses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientstatuses',
            table='client_statuses',
        ),
    ]
