# Generated by Django 4.1.1 on 2022-11-03 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clientstatuses_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatuses',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_client', to='clients.client', verbose_name='Клієнт'),
        ),
    ]
