# Generated by Django 4.1.1 on 2022-11-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clientstatuses_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsocialnetworks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='clientstatuses',
            name='id',
        ),
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='clientstatuses',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
    ]
