# Generated by Django 4.1.3 on 2022-11-18 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_remove_clientsocialnetworks_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_networks', serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='clientstatuses',
            name='client',
            field=models.OneToOneField(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_statuses', serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
    ]
