# Generated by Django 4.1.3 on 2022-11-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clientsocialnetworks_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='facebook',
            field=models.URLField(blank=True, max_length=128, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='instagram',
            field=models.URLField(blank=True, max_length=128, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='linkedin',
            field=models.URLField(blank=True, max_length=128, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='clientsocialnetworks',
            name='tictok',
            field=models.URLField(blank=True, max_length=128, verbose_name='Tik Tok'),
        ),
        migrations.AlterField(
            model_name='clientstatuses',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.client', verbose_name='Клієнт'),
        ),
    ]
