# Generated by Django 4.1.1 on 2022-11-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('Short-term', 'Короткостроковий'), ('Long-term', 'Довгостроковий'), ('Overdraft', 'Овердрафт'), ('Consumer', 'Споживчий'), ('Credit line', 'Кредитна лінія'), ('Secured by collateral', 'Забезпечений заставою')], default='Short-term', max_length=21, verbose_name='Тип договору'),
        ),
    ]
