# Generated by Django 4.1.1 on 2022-09-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='contract_sys_number',
        ),
    ]
