# Generated by Django 4.1.1 on 2022-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount_of_payments',
            field=models.IntegerField(default=0, verbose_name='Загальна сума виплат'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='commission',
            field=models.FloatField(default=0, verbose_name='Комісії'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro'), ('uah', 'Гривня')], default='uah', max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='current_debt',
            field=models.FloatField(default=0, verbose_name='Поточний борг'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='date_of_creation',
            field=models.DateField(help_text='01.01.2000', verbose_name='Дата заключення договору'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='delay_days',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кількість днів просрочки'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='fines',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Штрафи'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='initial_amount',
            field=models.FloatField(default=0, verbose_name='Початкова сума'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='interest',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Відсотки'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='last_payment_amount',
            field=models.FloatField(blank=True, default=0, max_length=8, null=True, verbose_name='Сума останнього платежу'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='monthly_payment_amount',
            field=models.FloatField(default=0, verbose_name='Сума щомісячного платежу'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='number_of_late_payments',
            field=models.IntegerField(default=0, verbose_name='Кількість прострочених платежів'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='payment_amounts',
            field=models.IntegerField(default=0, verbose_name='Кількість платежів'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='penalty',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Пеня'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='principal',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Основний борг'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='total_issued_amount',
            field=models.FloatField(default=0, verbose_name='Загальна сума виданих коштів'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='total_prolongation_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Загальна сума пролонгацій'),
        ),
    ]
