# Generated by Django 4.1.1 on 2022-09-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_alter_debt_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='debt',
            table='debt',
        ),
    ]
