# Generated by Django 4.1.1 on 2022-11-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_debt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('Короткостроковий', 'Короткостроковий'), ('Довгостроковий', 'Довгостроковий'), ('Овердрафт', 'Овердрафт'), ('Споживчий', 'Споживчий'), ('Кредитна лінія', 'Кредитна лінія'), ('Забезпечений заставою', 'Забезпечений заставою')], default='Короткостроковий', max_length=21, verbose_name='Тип договору'),
        ),
    ]
