# Generated by Django 4.1.1 on 2022-11-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_debt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='number_from_contractor',
            field=models.IntegerField(verbose_name='Номер договору в системі контрагента'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='origin_number',
            field=models.IntegerField(verbose_name='Оригінальний номер договору'),
        ),
    ]
