# Generated by Django 4.1.1 on 2022-09-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.JSONField(blank=True, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='post_address',
            field=models.JSONField(blank=True, null=True, verbose_name='Поштова адреса'),
        ),
    ]
