# Generated by Django 4.1.1 on 2022-10-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('UAH', 'Гривня')], default='UAH', max_length=3, verbose_name='Валюта'),
        ),
    ]
