# Generated by Django 4.1.1 on 2022-09-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_alter_contractor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='number_of_debts',
        ),
    ]
