# Generated by Django 4.1.1 on 2022-11-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_alter_debt_number_from_contractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='number_from_contractor',
            field=models.CharField(max_length=15, verbose_name='Номер договору в системі контрагента'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='origin_number',
            field=models.CharField(max_length=15, verbose_name='Оригінальний номер договору'),
        ),
    ]
