# Generated by Django 4.1.1 on 2022-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_remove_client_number_of_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оновлення'),
        ),
    ]
