# Generated by Django 4.1.1 on 2022-09-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_alter_client_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='contractor_manager',
        ),
    ]
